version: "2"
services:
  client:
    build: ../boxscore-client
    image: boxscore-client
    ports:
    - "8080:8080"
    depends_on:
    - web
  web:
    build: ./
    image: boxscore-api
    ports:
    - "8081:8081"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"